package com.oxygenxml.git.validation.internal.exception;

/**
 * Abstract exception generated by a validation process.
 * 
 * @author alex_smarandache
 *
 */
public class ValidationException extends Exception {
  
  /**
   * Constructor.
   * 
   * @param message The exception message.
   */
  public ValidationException(final String message) {
    super(message);
  }

}
